"""claimtable

Revision ID: ee9cf1bec13d
Revises: c9592e062d5b
Create Date: 2023-11-06 17:19:29.835429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9cf1bec13d'
down_revision = 'c9592e062d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_claims_item_id_items', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_claims_item_name_items'), 'items', ['item_name'], ['id'])
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_claims_item_name_items'), type_='foreignkey')
        batch_op.create_foreign_key('fk_claims_item_id_items', 'items', ['item_id'], ['id'])
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
